# Jacob Campbell's Personal Website

locale: "en-US"
title: "Jacob R. Campbell, ..."
email: your-email@example.com
description: "This site is my home for all of my stuff. I am an associate professor in the School of Social Work at Heritage University, long history of mental health and school social work, a Licensed Independent Clinical Social Worker, father, husband, and active community member"
name: "Jacob Campbell"

# Open Graph Settings
og_image: "/assets/media/2025-og-site-wide-fallback.jpg"

# Previously had >- this means to ignore newlines until "baseurl:"
# Baseurl will likely need to change when merged.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  campjacob

# Build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Conversion
markdown: kramdown

# When I transfer this to my website it will need to be /:collection/:path/
collections:
  presentations:
    output: true
    permalink: /:path/



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

whitelist:
  - jekyll-redirect-from

# Reading Files
include:
  - _pages
